spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic-name: novo_funcionario
      client-id: admin
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create